language: python
python:
#- '3.4'
- '3.5'
deploy:
#  - provider: pypi
#    server: https://testpypi.python.org/pypi
#    distributions: sdist bdist_wheel
#    user: lioman_test
#    password:
#      secure: "gbdUvZSFdd480mqMANycRwIu8qyBHhr6WYe3QRMSJbJO1HJ5QKzHpaCgyGLzbSPvyVMVviGEor1tOpWDwpZk8j+fj8fVubYaoXx61jvd4BHuXNRsVHaR3etNzI398yvZSa7NJXx+h69kqzQb9Q/98LxU4aUDkKF09ZATqHdae6OdBvU+4NCkCm0P9EDQU0TQqyVW1J4GQ0Af2Jwrp9R6baWaifVQvgLfBfCrFLmeZG0oHtLIX/91b6ANCWEmQ7bv8ENmFs5+HjLa53Ol1WZZtEJR+VSzQ6JIlB0AlvMYlnjUZVU4lRS/00vfEJv1l/OmzxxJhJ9Dybj6cxoOEjfEfZrnHiUAuRxbPfhzgXunfSo4bfBFJsuRKglp9JktTxHNqIldEypMYcZqTYXoCBIwxsmItB+7/y8jvQHIGjY23/B/zMMA2AolHwHIT6NoJ5Li/8rTJSKrY7rt490kotDxyEj+uRyC1jkUUDKfzTOwX0kp8UxcEnfjZO95qsYaVD9TKYMxOFgSNhYCu1LNI3onXD1WXX/4OfVI0JC4qfRtoVVCUIkahesW1FrKXv/OSrJ15DBrSCqizcRQd3alheEV6GxLbgD207SEeH9l5emDNZHz9IA5Wk2TyRnNJ2GEcwsngJwZ7oYzefaX0xgkkI1QsGgPhJEh0OOwMf2KqCitPy8="
#    on:
#      tags: false
#      branch: master
#      python: 3.5
  - provider: pypi
    distributions: sdist bdist_wheel
    user: lioman
    password:
      secure: "YWJHixbVoQ0Vuk9eq1FQ14ZfhYqL4h5EoJnqiHHfiwamAphcFgKQPYzwTi3hOm6LdeAxIw7RQB6SKpJQAdqTrIM6I5CIxDpabKRYSANsR01B+Lc0Rnam9PDsUGNhWTGm6npNsqaCcWwnfU+uZuqdVqJwaqTE1L+1tgycQHemw3Cal5S/OLmZ2vYSs9h2pQLGVOeliZUEHWHZkH4Zpl49g0H4E0Yi7Qt7fo1ITqg9dh81wTvB+wEQ9TGpCN1hlmikXAXkwckoTCmiSwkwlu24bn7cMV0xlPaXatRaVKtS3fbZk0omYob8ES/LFBDYb+kggZO4I4/Fu2BrzGamRRCLaTyiFiTyGLNgQuYWuepnHqsj7SV3YhT2d0GVDM3exYwjRqcjjYGUARBahd7Sl8hCO5i+IrAR3JNndbT7qUyCg8zXuFTQLqvitJbfuXLpemkL1lTvCU+HEUUVKlUV0tXi3n/3I+02DJynKiAFO9LL9sm8plRIV7VNi6XLsOATkQpnTl/018degkM9e6eJzF1719jpfbpjRfRlGacFdP8RENp+6XyxcGxT1yu0JEeX2/aEHO2CoPST+0UfOtXsjpoBI1JunVmyrveCwiWRVFpjwk2YCHKUO714jkJIbD3VJChWcu8ip2P+LRa0HHGM0Uq6a9oi051idEZ2a6GvOOLp6kA="
    on:
      tags: false
      repo: lioman/mendeley2biblatex
      branch: master
      python: 3.5
script: tox